---
title: "Reporting Guidelines"
output: 
  github_document:
    toc: true
    fig_width: 10.08
    fig_height: 6
  rmarkdown::html_vignette:
    toc: true
    fig_width: 10.08
    fig_height: 6
tags: [r, bayesian, posterior, test]
vignette: >
  \usepackage[utf8]{inputenc}
editor_options: 
  chunk_output_type: console
---

These guidelines can be referred to by citing the package:

- Makowski, D. (2019). *Understand and Describe Bayesian Models and Posterior Distributions using BayestestR*. Available from https://github.com/easystats/bayestestR. DOI:10.5281/zenodo.2556486.

# Reporting Guidelines

Based on the previous [**comparison of point-estimates**](https://easystats.github.io/bayestestR/articles/2_IndicesEstimationComparison.html) and [**indices of effect existence**](https://easystats.github.io/bayestestR/articles/3_IndicesExistenceComparison.html), we can conclude that:

- For simple models and normally distributed posteriors, the **MAP estimate** seems to be more biased than the mean and the median of the posterior distribution.
- Aside from being more robust, the **median** makes more sense than the **mean** in a probabilistic framework (*e.g.*, there is 50\% chance that the true effect is either higher or lower than the median).
- The **traditional ROPE** (using a 90\% HDI) is not sensitive to delineate highly "significant" effects. The full ROPE (100\% HDI) does not present the same flaw.
- The **Probability of Direction (*p*d)** is the closest index to the frequentist *p* value.

**Thus, to minimally describe the posterior distribution of a parameter, we suggest reporting the *median* and the *90\% CI* for parameter characterisation and, in the context of null-hypothesis testing, the Probability of Direction (*p*d) for effect existence and, especially in the context of confirmatory analyses, the ROPE (full) with an explicitly specified range for effect significance.**

## Interpretation Rules of Thumb

**The following thresholds are presented as landmarks only, for comparison with the frequentist framework. Please consider with caution.**

- **Probability of Direction (*p*d)**

    - *p*d \< 95\% ~ *p* \> .1: uncertain
    - *p*d \> 95\% ~ *p* \< .1: possibly existing
    - *p*d \> 97.5\% ~ *p* \< .05: likely existing
    - *p*d \> 99\% ~ *p* \< .01: probably existing
    - *p*d \> 99.9%\ ~ *p* \< .001: certainly existing

- **ROPE (full)**: Extra caution is required as its interpretation highly depends on other parameters such as sample size and ROPE bounds.

    - \> 99\% in ROPE: negligible (we can accept the null hypothesis)
    - \> 97.5\% in ROPE: probably negligible
    - \< 97.5\% - \> 2.5\% in ROPE: not significant
    - \< 2.5\% in ROPE: probably significant
    - \< 1\% in ROPE: significant (we can reject the null hypothesis)
    
*Note: If you have any advice, opinion or such, we encourage you to let us know by opening an [discussion thread](https://github.com/easystats/bayestestR/issues) or making a pull request.*

## Template Sentence

Based on these suggestions, a template sentence for minimal reporting of a parameter based on its posterior distribution could be:

- "the effect of *X* has a probability of ***p*d** of being *negative* (Median = ***median***, 90\% CI [***...***, ***...***]) and can be considered as *significant* (***ROPE***\% in ROPE)."