---
title: "Reporting Guidelines"
output: 
  github_document:
    toc: true
    fig_width: 10.08
    fig_height: 6
  rmarkdown::html_vignette:
    toc: true
    fig_width: 10.08
    fig_height: 6
tags: [r, bayesian, posterior, test]
vignette: >
  %\VignetteIndexEntry{Reporting Guidelines}
  \usepackage[utf8]{inputenc}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(knitr)
options(knitr.kable.NA = '')
knitr::opts_chunk$set(comment=">")
options(digits=2)
```


These guidelines can be referred to by citing the package:

- Makowski, D., Ben-Shachar M. S. \& Lüdecke, D. (2019). *Understand and Describe Bayesian Models and Posterior Distributions using bayestestR*. Available from https://github.com/easystats/bayestestR. DOI: [10.5281/zenodo.2556486](https://zenodo.org/record/2556486).

---

# Reporting Guidelines

Based on the previous [**comparison of point-estimates**](https://easystats.github.io/bayestestR/articles/indicesEstimationComparison.html) and [**indices of effect existence**](https://easystats.github.io/bayestestR/articles/indicesExistenceComparison.html), we can draw the following recommendations.

To minimally **describe the posterior distribution** of a parameter, we suggest reporting 1) the **median** as an index of centrality, 2) the **89\% CI** (using HDI rather than quantiles) as an index of centrality and, and in the context of null-hypothesis testing, the **Probability of Direction (*pd*)** or the ***Bayes factor*** for effect existence and, especially in the context of confirmatory analyses, either the **ROPE percentage** (full, *i.e.*, based on the full posterior distribution) with an explicitly specified range for effect significance.

# Effect *Existence* and *significance*

The ***pd***, the ***Bayes factor***, and the ***ROPE*** are three indices that give different and independent information: The ***pd*** is a marker of **existence**, consistency and direction of a parameter (whether a parameter has a consistent effect in one or another direction); the [Bayes factor](https://easystats.github.io/bayestestR/articles/bayes_factors.html) is a ratio, quantifying relative evidence for the **existence** of an effect, informing us by how much more (or less) the observed data is under two compared models - usually a model with an effect vs. a model without the effect; the percentage in **ROPE** is a index of **significance** (in its primary meaning), informing us whether a parameter is related or not to a non-negligible change (in terms of magnitude) in the outcome.

## Interpretation Rules of Thumb

**The following thresholds are presented as landmarks only, and any use of such "labels" should be explicitly justified. Please consider with caution.**

- **Probability of Direction (*p*d)**: In most cases, it seems that the *pd* corresponds to the frequentist one-sided *p* value through the formula `p value = (1-pd/100)` and to the two-sided *p* value (the most commonly reported) through the formula `p value = 2*(1-pd/100)`. Thus, a `pd` of `95%`, `97.5%` `99.5%` and `99.95%` corresponds approximately to a two-sided *p* value of respectively `.1`, `.05`, `.01` and `.001`. Thus, for convenience, we recommend using the following reference values:

    - *pd* **\<= 95\%** ~ *p* \> .1: uncertain
    - *pd* **\> 95\%** ~ *p* \< .1: possibly existing
    - *pd* **\> 97\%**: likely existing
    - *pd* **\> 99\%**: probably existing
    - *pd* **\> 99.9\%**: certainly existing

- **Bayes factor**: Generally, Bayes factors are continuous measures of relative evidence, with a Bayes factor greater than 1 giving evidence in favor of one of the models (the numerator), and a Bayes factor smaller than 1 giving evidence in favor of the other model (the denominator). Yet, it is common to interpret the **magnitude** of relative evidence based on [a convention of intervals](https://easystats.github.io/report/articles/interpret_metrics.html#bayes-factor-bf), such that the values of a *BF*<sub>10</sub> (comparing the alternative to the null) can be interpreted as:

    - *BF*<sub>10</sub> \< 1/100: Extreme evidence in favor of the null.
    - 1/100 \< *BF*<sub>10</sub> \< 1/30: Very strong evidence in favor of the null.
    - 1/30 \< *BF*<sub>10</sub> \< 1/10: Strong evidence in favor of the null.
    - 1/10 \< *BF*<sub>10</sub> \< 1/3: Moderate evidence in favor of the null.
    - 1/3 \< *BF*<sub>10</sub> \< 1: Anecdotal evidence in favor of the null.
    - 1 \< *BF*<sub>10</sub> \< 3: Anecdotal evidence in favor of the alternative.
    - 3 \< *BF*<sub>10</sub> \< 10: Moderate evidence in favor of the alternative.
    - 10 \< *BF*<sub>10</sub> \< 30: Strong evidence in favor of the alternative.
    - 30 \< *BF*<sub>10</sub> \< 100: Very strong evidence in favor of the alternative.
    - *BF*<sub>10</sub> \> 100: Extreme evidence in favor of the alternative.
    
(For human readability, it is recommended to report BFs so that the ratios are larger than 1 - for example, it's harder to understand a *BF*<sub>10</sub>\=0.07 (indicating the data are 0.07 times more probable under the alternative) than a *BF*<sub>01</sub>\=1/0.07\=14.3 (indicating the data are 14.3 times more probable under the null).

- **ROPE (full)**: Extra caution is required as its interpretation highly depends on other parameters such as sample size and ROPE range.

    - **\> 99\%** in ROPE: negligible (we can accept the null hypothesis)
    - **\> 97.5\%** in ROPE: probably negligible
    - **\<= 97.5\%** \& **\>= 2.5\%** in ROPE: undecided significance
    - **\< 2.5\%** in ROPE: probably significant
    - **\< 1\%** in ROPE: significant (we can reject the null hypothesis)
  

*Note: If you have any advice, opinion or such, we encourage you to let us know by opening an [discussion thread](https://github.com/easystats/bayestestR/issues) or making a pull request.*

## Template Sentence

Based on these suggestions, a template sentence for minimal reporting of a parameter based on its posterior distribution could be:

- "the effect of *X* has a probability of ***pd*** of being *negative* (Median = ***median***, 89\% CI [***...***, ***...***]) and can be considered as *significant* (***ROPE***\% in ROPE; $BF_{10} = $***BF***, indicating that the data is ... times more/less probable under the null)."