---
title: "Guidelines"
output: 
  github_document:
    toc: true
    fig_width: 10.08
    fig_height: 6
  rmarkdown::html_vignette:
    toc: true
    fig_width: 10.08
    fig_height: 6
tags: [r, bayesian, posterior, test]
vignette: >
  \usepackage[utf8]{inputenc}
editor_options: 
  chunk_output_type: console
---


# Reporting Guidelines

Based on the previous [**comparison of indices**](https://dominiquemakowski.github.io/bayestestR/articles/IndicesComparison.html), we can conclude that:

- For simple models and normally distributed posteriors, the **MAP estimate** seems to be more biased than the mean and the median of the posterior distribution.
- Aside from being more robust, the **median** makes more sense than the **mean** in a probabilistic framework (*e.g.*, there is 50% chance that the true effect is either higher or lower than the median).
- The **traditional ROPE** (95\% HDI) is not sensitive to delineate highly "significant" effects. The full ROPE (100\% HDI) does not present the same flaw.
- The **Probability of Direction (*p*d)** is the closest index to the frequentist *p* value.

**To minimally describe the posterior distribution of a parameter, we suggest reporting the *median* and the *90% CI (the 90% HDI)* for parameter characterisation and, in the context of null-hypothesis testing, the Probability of Direction (*p*d) for effect existence and, especially in the context of confirmatory analyses, the ROPE (full) with an explicitly specified range for effect significance.**

## Frequentist-like Arbitrary Thresholds

**The following thresholds are presented as landmarks only for comparison with the frequentist framework. Please consider with caution.**

- **Probability of Direction (*p*d)**

    - *p*d \< 95% ~ *p* \< .1: uncertain
    - *p*d \> 95% ~ *p* \< .1: possibly existing
    - *p*d \> 97.5% ~ *p* \< .05: likely existing
    - *p*d \> 99% ~ *p* \< .01: probably existing
    - *p*d \> 99.9% ~ *p* \< .001: certainly existing
    - *p*d = 100%: definitely existing

- **ROPE (full)**

    - Depends on other parameters such as sample size and ROPE bounds


*Note: If you have any advice, opinion or such, we encourage you to let us know by opening an [discussion thread](https://github.com/DominiqueMakowski/bayestestR/issues) or making a pull request.*